### ISSUE TITLE
arm

### ISSUE THREAD

**Issue by wangjiedlut** [awslabs/damo#31]
I run this program in aarch64 GNU/Linux environment, but it failed with the following logs:
```
[root@localhost damo-next]# sudo ./damo record -o damon.data $(pidof masim)
Traceback (most recent call last):
  File "./damo", line 91, in <module>
    main()
  File "./damo", line 70, in main
    record.main(args)
  File "/home/damo-next/record.py", line 158, in main
    _damon.chk_update_debugfs(args.debugfs)
  File "/home/damo-next/_damon.py", line 238, in chk_update_debugfs
    update_supported_features()
  File "/home/damo-next/_damon.py", line 168, in update_supported_features
    if test_debugfs_file(debugfs_target_ids, 'paddr\n', '42\n'):
  File "/home/damo-next/_damon.py", line 146, in test_debugfs_file
    f.write(input_str)
IOError: [Errno 16] Device or resource busy

```
My python version is Python 2.7.5， or I need to other lib ?

**Comment by wangjiedlut** [comment]
> 

It works after set the monitor_on off!

**Comment by sj-aws** [comment]
Thank you for quick confirmation!
